# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ dev-3 ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
workflow "All pushes" {
  on = "push"
  resolves = ["Deploy to Staging"]
}

action "Deploy to Staging" {
  uses = "contention/action-rsync-deploy@master"
  secrets = ["DEPLOY_KEY"]
  args = ["-avzr --delete", "--exclude .htaccess --exclude /uploads/", "user@server.com:/srv/myapp/public/htdocs/"]
} 